name: Ruby

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.7'
          - '3.1.6'
          - '3.2.4'
          - '3.3.3'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Appraisal install
        run: bundle exec appraisal install

      - name: Lint
        run: bundle exec rubocop
      - name: Build and test
        run: bundle exec appraisal rspec
